#!/bin/bash
PDFFILE=$1
osascript <<EOF
    if character 1 of "$PDFFILE" contains "~" then
      set PDFFILE to POSIX path of (path to home folder) & text (2 + (offset of "~" in "$PDFFILE")) thru -1 of "$PDFFILE"
    else
      set PDFFILE to POSIX path of "$PDFFILE"
    end if
    set FilePath to quoted form of PDFFILE
    set TheTitle to do shell script "basename " & FilePath
    set NumPages to last word of (do shell script "mdls " & FilePath & " | grep kMDItemNumberOfPages")
    set FileNotOpened to false
    tell application "System Events"
      if (exists of application process "Acrobat Pro 2017") then
        tell process "Acrobat Pro 2017"
          set frontmost to true
          if window TheTitle exists then
            tell window TheTitle to perform action "AXRaise"
            if NumPages is greater than 1 then
              keystroke "n" using {shift down, command down}
              keystroke "c" using {command down}
              keystroke tab
              keystroke return
            end if
            tell window TheTitle to perform action "AXPress" of (get value of attribute "AXCloseButton")
          else
            set FileNotOpened to true
          end if
        end tell
      else
        set FileNotOpened to true
      end if
    end tell
    do shell script "open -a \"Adobe Acrobat\" " & FilePath
    tell application "System Events"
      tell process "Acrobat Pro 2017"
        set frontmost to true
        if window TheTitle exists then
          tell window TheTitle to perform action "AXRaise"
          if NumPages is greater than 1 then
            if FileNotOpened then
              set the clipboard to "1"
            end if
            keystroke "n" using {shift down, command down}
            keystroke "v" using {command down}
            keystroke return
          end if
          keystroke "2" using {command down}
        else
          display dialog "Cannot open file " & quoted form of TheTitle
        end if
      end tell
    end tell
EOF
