#!/bin/bash
FILE=$1
PDFFILE="$(pwd)/${FILE}"
osascript <<EOF
    set FilePath to quoted form of POSIX path of "$PDFFILE"
    try
      set TheTitle to (do shell script "basename " & FilePath)
      set NumPages to (do shell script "/opt/local/bin/qpdf --show-npages " & FilePath)
      set PageSize to (do shell script "/opt/local/bin/pdfinfo " & FilePath & " | grep \"Page size\" | grep -Eo '[-+]?[0-9]*\\\.?[0-9]+'")
      set PageWidth to word 1 of PageSize
      set PageHeight to word 2 of PageSize
      if PageWidth is less than PageHeight then
        set LetterSize to true
      else
        set LetterSize to false
      end if
    on error ErrMsg number ErrNum
      display dialog ErrMsg & ": code " & ErrNum
    end try
    set FileNotOpened to false
    tell application "System Events"
      if (exists of application process "Acrobat Pro DC") then
        tell application process "Acrobat Pro DC"
          set frontmost to true
          try
            if window TheTitle exists then
              tell window TheTitle to perform action "AXRaise"
              if NumPages is greater than 1 then
                keystroke "n" using {shift down, command down}
                -- keystroke "c" using {command down}
                -- keystroke tab
                -- keystroke return
                set PageNumber to value of text field of window "Go To Page"
                click button "Cancel" of window "Go To Page"
              end if
              tell window TheTitle to perform action "AXPress" of (get value of attribute "AXCloseButton")
            else
              set FileNotOpened to true
            end if
          on error ErrMsg number ErrNum
            display dialog ErrMsg & ": code " & ErrNum
          end try
        end tell
      else
        set FileNotOpened to true
      end if
    end tell
    do shell script "open -a \"Adobe Acrobat\" " & FilePath
    tell application "System Events"
      tell application process "Acrobat Pro DC"
        set frontmost to true
        if window TheTitle exists then
          tell window TheTitle to perform action "AXRaise"
          if NumPages is greater than 1 then
            if FileNotOpened then
              -- set the clipboard to "1"
              set PageNumber to "1"
            end if
            keystroke "n" using {shift down, command down}
            -- keystroke "v" using {command down}
            -- keystroke return
            set value of text field of window "Go To Page" to PageNumber
            click button "OK" of window "Go To Page"
            if FileNotOpened then
              if (menu item "Previous Page" of menu "Page Navigation" of menu item "Page Navigation" of menu "View" of menu bar item "View" of menu bar 1) exists then
					      click (menu item "Previous Page" of menu "Page Navigation" of menu item "Page Navigation" of menu "View" of menu bar item "View" of menu bar 1)
				      end if
            end if
          end if
          if LetterSize then
            keystroke "2" using {command down}
          end if
        else
          display dialog "Cannot open file " & TheTitle
        end if
      end tell
    end tell
EOF
