#!/usr/bin/python

import sys, os.path
from subprocess import Popen

# Check we have (only) one argument
if len(sys.argv) != 2:
    sys.exit(1)

# Argument one is supposed to be the PDF file
pdf_file = os.path.abspath(sys.argv[1])

# Check whether the file exists & is readable
if not os.path.isfile(pdf_file):
    sys.exit(1)

# Notwithstanding the previous, start evince and open the PDF
vproc = Popen(['acrobatread', pdf_file])
vproc.wait()
